# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
# ~> https://gitter.im/minicomp/wax/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'Unstable Archives'
description:      'PLACEHOLDING'
url:              'https://maxjdugan.github.io/unstable_archives/'
baseurl:          '/unstable_archives'
copyright:        'Megan Eaton Robb'
logo:             '/assets/pendant_transparent.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  unstable_archives: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'unstable_archives_item' # the layout for the pages to use
    metadata:
      source: 'unstable_archives.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/ua_directory' # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      unstable_archives:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - label
          - summary
          - contents
          - keyword1
          - keyword2
          - keyword3
          - keyword4
          - keyword5
          - keyword6
          - keyword7
          - keyword8
          - keyword9
          - keyword10
          - keyword11
          - object_type1
          - object_type2
          - object_type3
          - shelfmark
          - metadata_creators
          - repository_city
          - roles
          - _date
          - place_origin
          - provenance_details
          - language
          - decoration
          - layout
          - hand_script
          - dimensions
          - additional_info
          - notes_digitizer
          - copyright_statement
          - images

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'About'
    sub:
      - label: 'Wax'
        link: '/about/'
      - label: 'Documentation'
        link: 'https://minicomp.github.io/wiki/wax/'
      - label: 'Credits'
        link: '/credits/'
  - label: 'Exhibits'
    sub:
      - label: 'UA_SNED_25 W/O TEI'
        link: '/exhibits/a/'
      - label: 'UA_SNED_25 W/TEI'
        link: '/exhibits/b/'
  - label: 'Browse'
    link: '/collection/'
  - label: 'Search'
    link: '/search/'
  - label: 'Reuse'
    link: '/reuse/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'GitHub'
      link: 'https://github.com/minicomp/wax'
    - label: 'Credits'
      link: '/credits'
    - label: 'Contact'
      link: 'https://gitter.im/minicomp/wax/'
  logos:
    - img: '/img/pendant_transparent.png'

# FIN
